version: '3'

services:
  recipes-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipes-app
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - API_URL=http://192.168.85.50:9000
    networks:
      - recipes-network

networks:
  recipes-network:
    driver: bridge